name: Test TurboRepo Remote Cache

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-cache:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout test repo
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Start TurboRepo Remote Cache
        uses: freddyfallon/turbo-remote-cache-action@main
        with:
          storage-provider: 'local'
          team-id: 'test-team'
          
      - name: First build (should miss cache)
        run: npm run build
        
      - name: Second build (should hit cache)  
        run: npm run build
        
      - name: Test commands
        run: npm run test
        
      - name: Lint commands
        run: npm run lint